<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>MEOW MEDIA GROUP — Международное агентство мобильного маркетинга</title>
    <meta name="description"
        content="Привлекаем качественную аудиторию на каждом этапе воронки продаж. Прикладной опыт продвижения от роста узнаваемости до покупки" />
    <script async src="https://www.google.com/recaptcha/api.js?render=6LdDA1IrAAAAAAR9hSFORDO7Yd_wRCHcPxiw5BBj">
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"
        integrity="sha512-7eHRwcbYkK4d9g/6tD/mhkf++eoTHwpNM9woBxtPUBWm67zeAfFC+HrdoE2GanKeocly/VxeLvIqwvCdk7qScg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"
        integrity="sha512-onMTRKJBKz8M1TnqqDuGBlowlH0ohFzMXYRNebz+yOcc5TQr/zAKsthzhuv0hiyUKEiQEQXEynnXCvNTOk50dg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://unpkg.com/gsap@3/dist/ScrollToPlugin.min.js" crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>
    <link type="image/x-icon" href="/favicon.ico" rel="shortcut icon" />
    <link rel="icon" href="/favicon.ico" />
    <link type="text/css" rel="stylesheet" href="css/styles.css" />
    <link type="text/css" rel="stylesheet" href="css/menu.css" />
    <link type="text/css" rel="stylesheet" href="css/modal.css" />
    <link type="text/css" rel="stylesheet" href="css/forms.css" />
    <link type="text/css" rel="stylesheet" href="css/cases.css" />

    <script src="/js/script.js"></script>

</head>

<body class="body_bg_mm">
    <!-- <div class="preloader" id="preloader">
        <div class="spinner"></div>
    </div> -->
    <?php include 'inc_menu_hamburger.phtml'; ?>
    <header id="header" class="vacancy">
        <div class="header-content-container">
            <nav role="navigation" class="menu_container">
                <a href="/"><img src="./img/logo_2x.png" alt="Meow Media Group" id="logo-img" /></a>
                <?php include 'inc_menu_desktop.phtml'; ?>

                <div class="menu_mobile">
                    <div id="menuToggle">
                        <input type="checkbox" id="menuCheckbox" />
                        <span></span>
                        <span></span>
                        <span></span>
                        <div>&nbsp;</div>
                    </div>
                </div>
            </nav>
        </div>
    </header>


    <div class="main-content moneyman_bg">
        <div id="scrollToTop" class="scroll-top">
            <img src="/img/icon_up.png" alt="Вверх" width="35" height="35" />
        </div>
        <?php include 'forms_feedback1.phtml'; ?>

        <div class="section section_transparent section_moneyman_top section_moneyman">
            <div class="container">
                <div class="container_1">
                    <div class="moneyman_cat">
                        <img src="./img/cases/moneyman_cat.png" alt="Moneyman" />
                    </div>
                    <div class="punkts__logo">
                        <img src="./img/cases/moneyman_logo3x.png" alt="Moneyman" />
                    </div>
                    <h2 class="str1">рост займов новым клиентам</h2>
                    <h2 class="str2">в 15 раз</h2>

                    <div class="case_desc">
                        Moneyman — один из ведущих онлайн-сервисов альтернативного кредитования в России.
                    </div>
                    <div class="case_top_buffer1">&nbsp;</div>
                </div>

                <div class="cards_container">
                    <div class="card">
                        <h3 class="color-blue">Запрос</h3>
                        <p>
                            Компания пришла с запросом увеличить число займов для новых клиентов через мобильное
                            приложение. У
                            Moneyman уже были готовые креативы и позиционирование — нужно было доставить этот месседж
                            широкой
                            целевой аудитории компании.
                        </p>
                        <p>
                            <strong>Целевым действием</strong> мы сделали выдачу займа новому клиенту. Moneyman были
                            нужны не просто
                            клики по рекламе или установки приложения, а именно займы новым заказчикам — поэтому мы
                            поставили в KPI
                            то, что решало их задачу.
                        </p>
                    </div>
                    <div class="card" style="position: relative">
                        <h3 class="color-blue">Решение</h3>
                        <p><i>Мы запустили кампанию по двум основным направлениям:</i></p>
                        <p>
                            <strong class="color-blue">Классический in-app</strong> — реклама внутри приложений,
                            таргетированная на
                            целевую аудиторию
                        </p>
                        <p>
                            <strong class="color-blue">Трафик из премиум-источников</strong> — площадок вроде Huawei,
                            Xiaomi, Unity,
                            IronSource, AppLovin, Bigo и др. Такой трафик дороже, зато качественный и прозрачный. Фрода
                            здесь
                            намного меньше, чем в других источниках, так что клиент не платит за мошеннические действия,
                            а получает
                            реальных пользователей. Более того, в рекламных кабинетах премиум-источников можно видеть
                            стоимость
                            любого события и отслеживать все этапы конверсии.
                        </p>
                        <div class="klubok_resh1"><img src="/img/cases/moneyman_klubok.png" width="150" alt="icon" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="section section_transparent section_moneyman_2">
            <div class="container">
                <div class="punkts__content">
                    <div class="punkts__info item1">
                        <span class="punkts__name">Платформы:</span>
                        <span class="punkts__value">iOS, Android.</span>
                    </div>
                    <div class="items23">
                        <div class="punkts__info item2">
                            <span class="punkts__name">Гео:</span>
                            <span class="punkts__value">Россия</span>
                        </div>

                        <div class="punkts__info item3">
                            <span class="punkts__name">Трекер:</span>
                            <span class="punkts__value">Appsflyer</span>
                        </div>
                    </div>
                    <div class="punkts__info item4">
                        <span class="punkts__name">Событие:</span>
                        <span class="punkts__value">выдача займа новому клиенту</span>
                    </div>

                    <div class="punkts__info item5">
                        <span class="punkts__name nowrap">Источники трафика:</span>
                        <span class="punkts__value">managed in-app, Unity, Bigo, Appnext.</span>
                    </div>
                    <div class="punkts__info item6">
                        <span class="punkts__name">Антифрод-решение:</span>
                        <span class="punkts__value">Protect360</span>
                    </div>

                    <div class="punkts__info item7">
                        <span class="punkts__name">Период рекламной кампании:</span>
                        <span class="punkts__value">июнь 2024 — по настоящее время.</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="section section_moneyman_real section_moneyman">
            <div class="container" style="position: relative">
                <div class="klubok_real"><img src="/img/cases/moneyman_klubok.png" width="150" alt="icon" /></div>
                <div>
                    <h2>Реализация</h2>
                </div>
                <div class="timeline">
                    <div class="timeline-item">
                        <div class="timeline-content">
                            <h4><span class="color-blue">Мы подобрали оптимальный сплит</span> источников трафика:</h4>
                            <ul class="star-list">
                                <li>
                                    Первые рекламные кампании были запущены через премиальные сети Bigo, Unity и
                                    Appnext, которые
                                    предлагают продвинутые возможности для таргетинга и персонализации.
                                </li>
                                <li>
                                    Для дальнейшего масштабирования мы подключили managed inapp-сети, что стало отличным
                                    инструментом
                                    для масштабирования.
                                </li>
                                <li>
                                    В процессе работы был сформирован white-лист источников managed inapp, которые
                                    соответствуют
                                    заданным стандартам качества и удерживают уровень фрода в рамках требований — не
                                    более 15% по
                                    Protect360.
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="timeline-item">
                        <div class="timeline-content">
                            <h4><span class="color-blue">Настроили таргетинги</span> по гео и соцдему:</h4>
                            <ul class="star-list">
                                <li>
                                    <strong>Соцдем:</strong> люди 21-45 лет, в том числе с детьми, поскольку у них часто
                                    возникает
                                    потребность в быстром займе для незапланированных расходов.
                                </li>
                                <li>
                                    <strong>География:</strong> фокус на регионы с большой плотностью населения и
                                    невысоким средним
                                    уровнем дохода — именно там выше потребность в быстром простом финансировании.
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="timeline-item">
                        <div class="timeline-content">
                            <h4 class="color-blue">Оптимизировали кампанию по фроду:</h4>
                            <p>
                                Конверсию из клика в установку, из установки в событие, наличие всех событий по воронке
                                и др. В
                                процессе корректировали настройки, увеличивая долю наиболее эффективных источников.
                            </p>
                        </div>
                    </div>
                    <div class="timeline-item">
                        <div class="timeline-content">
                            <h4 class="color-blue">Запустили кампанию и начали отслеживать ее ход и показатели:</h4>
                            <ul class="star-list">
                                <li>
                                    При запуске классического in-app маркетинга использовали блэклисты — списки
                                    источников, известных
                                    своими фродерскими действиями. Помимо уже существующих списков, мы используем наш
                                    внутренний
                                    блэк-лист площадок.
                                </li>
                                <li>
                                    Подключили решение <strong>Protect360</strong> — инструмент от AppsFlyer, который
                                    защищает от
                                    мошенничества, связанного с атрибуцией.
                                </li>
                                <li>
                                    <strong>Ручной контроль:</strong> в ходе кампании мониторили ключевые метрики на
                                    предмет аномалий —
                                    подозрительных всплесков активности, необычной географии или пользовательских
                                    устройств. Все это
                                    может говорить о фроде от источника.
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="section section_transparent section_moneyman_result section_moneyman">
            <div class="container">
                <div class="uz_container2">
                    <h2>Результат</h2>
                    <p>
                        <strong>Подводить итоги еще рано:</strong> мы продолжаем работать с Moneyman, а наши показатели
                        растут с
                        каждым месяцем.
                    </p>
                    <p>Вот чего мы смогли достичь за первые 8 месяцев работы:</p>
                </div>
                <div class="cards_container2">
                    <div class="card one">
                        <div>Рост целевых <br />действий в 15 раз!</div>
                        <div>120 → 1852 в месяц</div>
                    </div>
                    <div class="card two">
                        <div><strong>Число установок</strong></div>
                        <div>4,6 тыс. → 27,9 тыс.</div>
                        <div>Рост в 6 раз!</div>
                    </div>
                    <div class="card three">
                        <div>Cнижение стоимости <br />привлечения клиента</div>
                        <div>НА 12%</div>
                        <br />
                        <div class="klubok_result"><img src="/img/cases/moneyman_klubok.png" width="150" alt="icon" />
                        </div>
                    </div>
                    <div class="card four">
                        <div><strong>Результаты оптимизации медиасплита:</strong></div>
                        <div>
                            Доля premium in-app составляет 45% медиасплита → Фрод сведен к минимуму, а трафик стал
                            качественнее и
                            прозрачнее
                        </div>
                    </div>
                </div>
                <div><br /><br /><br /><br /></div>
            </div>
        </div>
        <?php include 'footer.phtml'; ?>
    </div>
</body>

</html>